name: CD-3-Release-Oficial
on:
  push:
    tags: [ 'v*' ] # Filtro de etiqueta 
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mvn package -DskipTests
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.war