name: CD-5-Notificador-Estado
on: [workflow_dispatch]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Log status
        run: |
          echo "Despliegue completado con Ã©xito"
          echo "Fecha: $(date)"
          echo "Autor: ${{ github.actor }}" # Variable de entorno solicitada 