name: CD-6-Despliegue-SSH
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mvn package -DskipTests
      - name: SCP Transfer
        uses: appleboy/scp-action@v0.1.7 # Acci√≥n recomendada 
        with:
          host: ${{ secrets.REMOTE_IP }} # Secreto configurado 
          key: ${{ secrets.SSH_KEY }}
          source: "target/*.war"
          target: "/home/usuario/despliegues"