name: CD-7-Flujos-Encadenados
on:
  workflow_run:
    workflows: ["CI-1-Vigilante-Universal"] # Detecta el CI 
    types: [completed]
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Solo si CI tuvo éxito 
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI pasó correctamente. Iniciando CD..."